version: 2
project_name: estacao-atlas

builds:
  - id: linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: windows
    env:
      - CGO_ENABLED=0
    tags:
      - ebitenexternaldll
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

release:
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
